"""create freebies table

Revision ID: 48104bd05d53
Revises: 5f72c58bf48c
Create Date: 2025-05-24 11:47:35.105801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48104bd05d53'
down_revision = '5f72c58bf48c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
